### ISSUE TITLE
Custom View doesn't show on iOS despite proper configuration

### ISSUE THREAD

**Issue by ThasianX** [Expensify/react-native-share-menu#73] opened 2020-08-19 04:43 UTC
Relevant repository: https://github.com/ThasianX/YoutubeToSpotify-React-Native/tree/feature/react-native-share-menu

It's hard to pinpoint the issue because I'm getting no errors from the console or XCode. It builds the `index.share.js` component fine it doesn't display it. I would appreciate it if anyone could just clone the repository and try debugging what is causing the issue.

**Comment by LPitonakova** [comment] 2020-09-28 19:38
I have the same problem. Only a white popup shows up, but nothing is in it. Also, I am getting the share item to be null. Did you manage so solve this problem?

**Comment by doreprogramer** [comment] 2020-09-30 10:57
Same problem here.

**Comment by igez** [comment] 2020-10-19 14:32
I was having similar issue, after fiddle some hours I made stupid mistake, I put index.share.js inside src folder, it should be on root folder, after moving it to root folder, it works as expected!

**Comment by Sergey2095** [comment] 2020-11-16 11:06
I had same behaviour till do all steps from this section https://github.com/meedan/react-native-share-menu/blob/master/SHARE_EXTENSION_VIEW.md. In my case I forget to add ReactShareViewController in "share target" folder.

**Comment by Gustash** [comment] 2020-11-16 13:42
@ThasianX I cloned your repo and the problem is that you're trying to use the `Pressable` component on React Native 0.62, but that component was introduced on 0.63.

You'll see errors on the Xcode console if you run the share target manually. Select the Share target instead of the app target and choose an app to share from. You'll then get debug logs from the Share Extension.

**Closed as completed by Gustash** 2020-11-16 13:42 UTC
Labels: ios
