### ISSUE TITLE
Cannot get shared text when app is running. Need to kill app to get updated value of shared text.

### ISSUE THREAD

**Issue by kartikpr** [Expensify/react-native-share-menu#43] opened 2019-11-20 21:03 UTC
Using version 2.2.2
Tried making launchMode = "singleTop" and adding android:documentLaunchMode="never" but it doesn't help
Did anyone get this to work?
thanks in advance :)

**Comment by caiosba** [comment] 2019-11-21 01:52
Closing as a duplicate of #39 :)

**Closed as completed by caiosba** 2019-11-21 01:52 UTC
Labels: duplicate
